---
#
# Default configuration for playbooks included in this repository
#

# === Java
java_distribution: corretto
java_package: jdk
java_major_version: 11
java_arch: x64

# === NodeJS
nodejs_version: "16.x"

# === PHP
php_version: '8.0'
php_packages:
  - php
  - php-cli
  - php-common
  - php-mysql
  - php-xml
  - php-xmlrpc
  - php-curl
  - php-imap
  - php-mbstring
  - php-soap
  - php-zip
  - php-intl
  - php-bcmath
  - php-gd
  - php-imagick
  - php-dev
php_xdebug_version: 3.1.3
php_xdebug_remote_port: "9003"
php_xdebug_idekey: PHPSTORM

# === Keyboard layout settings
keyboard_model: pc105
keyboard_layout: de

# === Language settings
locale_lang: de_DE.UTF-8
